// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eovxoexkqfqngtqhwmii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvdnhvZXhrcWZxbmd0cWh3bWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzI1OTIsImV4cCI6MjA2Nzc0ODU5Mn0.eRbmprRMcZ3V9_abeeF8_eYSmTZ_JUhvsR-taJ8Id_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});